### ISSUE TITLE
Hello, there was an error when I was training with a single gpu

### ISSUE THREAD

**Issue by luoyq6** [liming-ai/AlignDet#11]
Hello, there was an error when I was training with a single gpu，RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by liming-ai** [comment]
> Hello, there was an error when I was training with a single gpu，RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

Hi, what command are you using? The example we provide in the README needs 8 GPUs, if you want to run with one GPU, make sure you have adjusted the learning rate, and then try:
```
bash tools/dist_train.sh configs/selfsup/mask_rcnn.py 1 --work-dir work_dirs/selfsup_mask-rcnn
```

For more details about how to use mmdet, please refer to their repo and tutorials.
