### ISSUE TITLE
Hello, can your algorithm be trained with mixed precision

### ISSUE THREAD

**Issue by luoyq6** [liming-ai/AlignDet#15]
Hello, can your algorithm be trained with mixed precision, Does it support mixed precision training? I tried to modify the parameters, but it doesn't seem to work

**Comment by luoyq6** [comment]
@liming-ai I tried that. It didn't work, you know

**Comment by liming-ai** [comment]
> @liming-ai I tried that. It didn't work, you know

Please tell me your environment, running command and detailed error report.

**Comment by luoyq6** [comment]
@liming-ai Hello, thank you for your timely reply, can you add your contact information? Now I have reduced the input size and it is running, and I do not know which environment is used at present, I will contact you after he finishes training? How's it going? Are you in China?
