### ISSUE TITLE
Pretrain

### ISSUE THREAD

**Issue by wangsun1996** [liming-ai/AlignDet#17]
When I run:`tools/dist_train.sh configs/selfsup/mask_rcnn.py 8 --work-dir work_dirs/selfsup_mask-rcnn`
Q1:i Think Image-domain and Box-domain pre-training only update Neck&Head,didn't update backbone,is ture?
Q2:AlignDet only pre-training a model's Neck&Head.Backbone is frozen whole training process.Is true?
Q3:Backbone is only update in fine-tune process，is ture?
Thank you

**Comment by liming-ai** [comment]
Q1: The Image-domain only pre-train the backbone, the Box-domain only update Neck&Head
Q2: Backbone is frozen during the the Box-domain stage
Q3: Backbone is updated both in the Image-domain pre-train stage and the fine-tuning stage

> When I run:`tools/dist_train.sh configs/selfsup/mask_rcnn.py 8 --work-dir work_dirs/selfsup_mask-rcnn` Q1:i Think Image-domain and Box-domain pre-training only update Neck&Head,didn't update backbone,is ture? Q2:AlignDet only pre-training a model's Neck&Head.Backbone is frozen whole training process.Is true? Q3:Backbone is only update in fine-tune process，is ture? Thank you
