### ISSUE TITLE
mmdet框架下的模型能否用于ultralytic的YOLO系列做预训练模型？

### ISSUE THREAD

**Issue by Nabyssache** [liming-ai/AlignDet#2]
final-model.pth 能否用于YOLO框架下做与训练模型呢？

**Comment by liming-ai** [comment]
> final-model.pth 能否用于YOLO框架下做与训练模型呢？

AlignDet is a general method that can be adapted to various object detection models, including YOLO. Unfortunately, we have no plans to extend it to other codebases, currently only mmdet is supported
