### ISSUE TITLE
where can i download the file 'train2017_ratio3size0008@0.5_cluster-id-as-class.json' in configs\selfsup\detr.py

### ISSUE THREAD

**Issue by smarengin** [liming-ai/AlignDet#3]
nice work, thank you!

**Comment by liming-ai** [comment]
> nice work, thank you!

Thanks for the report, I will fix this issue.

**Comment by liming-ai** [comment]
> nice work, thank you!

Thanks for the report, we have added this file into google drive, you can check it now at [here](https://drive.google.com/file/d/1HnDNzax2p1ZES5AS1xUOgPMNfhvyAcjA/view)
