### ISSUE TITLE
about the pseudo-semantic labels of DETR

### ISSUE THREAD

**Issue by smarengin** [liming-ai/AlignDet#5]
do you run the experiments when training DETR without using cluster results as the pseudo-semantic labels? is the perfermance degrade much?
thank you!

**Comment by liming-ai** [comment]
> 

Yes, the results of DETR without using cluster results as the pseudo-semantic labels will lead to poor performance, due to the Hungarian Algorithm needing explicit class information to achieve one-one matching.
