### ISSUE TITLE
Hi, I have some questions about data set partitioning.

### ISSUE THREAD

**Issue by luoyq6** [liming-ai/AlignDet#6]
![85b519c3810fc2a388d5d2cc8344a39](https://github.com/liming-ai/AlignDet/assets/110521846/31f3614c-2c75-4a90-9ce8-8eba9acb5831)
As shown in the figure above, in the results of this table, does the pre-training Data except backbone include the 1% Data that is fine-tuned

**Comment by liming-ai** [comment]
> ![85b519c3810fc2a388d5d2cc8344a39](https://user-images.githubusercontent.com/110521846/257769790-31f3614c-2c75-4a90-9ce8-8eba9acb5831.png) As shown in the figure above, in the results of this table, does the pre-training Data except backbone include the 1% Data that is fine-tuned

Hi, this result means we pre-train the neck & head on the coco train dataset, and then fine-tuned the whole model with 1% coco images and annotations

**Comment by liming-ai** [comment]
Feel free to re-open this issue if you have more questions
