### ISSUE TITLE
How can I get filtered_proposals for a custom dataset?

### ISSUE THREAD

**Issue by lclin-ustc** [liming-ai/AlignDet#9]
Very nice and useful work! I want to pre-train a model for a custom dataset, so how can I get filtered proposals for my own dataset? Can you release the code for it? Thank you very much.

**Comment by lclin-ustc** [comment]
Oh, you use the same selective search code and filtering strategy as SoCo. And I found it in https://github.com/hologerry/SoCo

**Comment by liming-ai** [comment]
> Oh, you use the same selective search code and filtering strategy as SoCo. And I found it in https://github.com/hologerry/SoCo

Yes, we use the same code and filtering strategy as SoCo for the selective search proposals. However, the resulting proposals may not be exactly the same due to the environment and the random seed. If you want to fully reproduce the results of AlignDet, please use our released proposals. Feel free to re-open this issue~

**Comment by wangsun1996** [comment]
> Very nice and useful work! I want to pre-train a model for a custom dataset, so how can I get filtered proposals for my own dataset? Can you release the code for it? Thank you very much.

I read the questions on the discussion board，then i use SOCO code to get my custom dataset's filtered_proposals. SOCO code as this:
### Prepare data with Selective Search
1. Generate Selective Search proposals
    ```shell
    python selective_search/generate_imagenet_ss_proposals.py
    ```
2. Filter out invalid proposals with filter strategy
    ```shell
    python selective_search/filter_ss_proposals_json.py
    ```
3. Post preprocessing for images of no proposals
    ```shell
    python selective_search/filter_ss_proposals_json_post_no_prop.py
But I found that my [train_ratio3size0008@0.5.json](mailto:train_ratio3size0008@0.5.json) format are not the same as the coco dataset author provided(Google Drive). How can i get the right format of [train_ratio3size0008@0.5.json](mailto:train_ratio3size0008@0.5.json) to use Aligndet training . Could you provide this code? Where did I go wrong？ Thank you very much!
